In [1]:
import numpy as np
import seaborn as sns
from bokeh.io import output_file, show, curdoc
from bokeh.plotting import figure

In [ ]:
# load dataset car_crashes

car_df = sns.load_dataset("car_crashes")
car_df

In [3]:
# create numpy array from dataset

car_arr = np.array(car_df)
car_arr

array([[18.8, 7.332000000000001, 5.64, 18.048, 15.04, 784.55, 145.08,
        'AL'],
       [18.1, 7.421, 4.525, 16.290000000000003, 17.014, 1053.48, 133.93,
        'AK'],
       [18.6, 6.51, 5.208000000000001, 15.624, 17.856, 899.47, 110.35,
        'AZ'],
       [22.4, 4.032, 5.824, 21.056, 21.28, 827.34, 142.39, 'AR'],
       [12.0, 4.2, 3.36, 10.92, 10.68, 878.41, 165.63, 'CA'],
       [13.6, 5.032, 3.808, 10.743999999999998, 12.92, 835.5, 139.91,
        'CO'],
       [10.8, 4.968, 3.888, 9.396, 8.856, 1068.73, 167.02, 'CT'],
       [16.2, 6.156000000000001, 4.86, 14.094, 16.038, 1137.87, 151.48,
        'DE'],
       [5.9, 2.006, 1.5930000000000002, 5.9, 5.9, 1273.89, 136.05, 'DC'],
       [17.9, 3.759, 5.190999999999999, 16.468, 16.826, 1160.13, 144.18,
        'FL'],
       [15.6, 2.964, 3.9, 14.82, 14.508, 913.15, 142.8, 'GA'],
       [17.5, 9.45, 7.175, 14.35, 15.225, 861.18, 120.92, 'HI'],
       [15.3, 5.508000000000001, 4.437, 13.005, 14.994000000000002,
        641.96, 8

In [4]:
# create new numpy array with only 3 columns

car_arr3 = car_arr[:,:3]
car_arr3

array([[18.8, 7.332000000000001, 5.64],
       [18.1, 7.421, 4.525],
       [18.6, 6.51, 5.208000000000001],
       [22.4, 4.032, 5.824],
       [12.0, 4.2, 3.36],
       [13.6, 5.032, 3.808],
       [10.8, 4.968, 3.888],
       [16.2, 6.156000000000001, 4.86],
       [5.9, 2.006, 1.5930000000000002],
       [17.9, 3.759, 5.190999999999999],
       [15.6, 2.964, 3.9],
       [17.5, 9.45, 7.175],
       [15.3, 5.508000000000001, 4.437],
       [12.8, 4.6080000000000005, 4.352],
       [14.5, 3.625, 4.205],
       [15.7, 2.669, 3.925],
       [17.8, 4.806, 4.272],
       [21.4, 4.066, 4.922],
       [20.5, 7.175, 6.765],
       [15.1, 5.738, 4.53],
       [12.5, 4.25, 4.0],
       [8.2, 1.886, 2.87],
       [14.1, 3.384, 3.948],
       [9.6, 2.208, 2.784],
       [17.6, 2.64, 5.456],
       [16.1, 6.923000000000001, 5.474000000000001],
       [21.4, 8.345999999999998, 9.416],
       [14.9, 1.9370000000000005, 5.215],
       [14.7, 5.439, 4.704],
       [11.6, 4.06, 3.48],
       [11.2, 1

In [5]:
class Zscore:

    def __init__(self, np_columns: np.ndarray):
        self.car_arr3 = car_arr3

    def get_score(self, x):
        arr = []
        for i in x:
            z = abs((i - np.mean(x)) / np.std(x))
            arr.append(z)

        return np.array(arr)


In [6]:
scores = Zscore(car_arr3)

In [7]:
def get_average_score(x, y, z):
    return np.average([x,y,z])

In [8]:
# calculate z-score for each of column

z_total = scores.get_score(car_arr3[:,0])
z_total

array([0.73744574, 0.56593556, 0.68844283, 1.61949811, 0.92865317,
       0.5366299 , 1.22267063, 0.10040792, 2.42324191, 0.51693265,
       0.04660081, 0.41892683, 0.12010517, 0.73264154, 0.31611681,
       0.02209935, 0.4924312 , 1.37448356, 1.15397047, 0.16910808,
       0.8061459 , 1.85970845, 0.41412263, 1.51668808, 0.44342829,
       0.07590647, 1.37448356, 0.21811099, 0.2671139 , 1.02665899,
       1.12466481, 0.63943992, 0.85514881, 0.24741665, 1.98701993,
       0.41412263, 1.00696174, 0.73264154, 0.59043701, 1.14916626,
       1.98701993, 0.88445447, 0.90895592, 0.88445447, 1.10016336,
       0.5366299 , 0.75714299, 1.27167354, 1.96251847, 0.48762699,
       0.39442538])

In [9]:
z_speed = scores.get_score(car_arr3[:, 1])
z_speed

array([1.1681476 , 1.2126951 , 0.75670887, 0.48361373, 0.39952407,
       0.01692   , 0.01511416, 0.57951992, 1.49769509, 0.62025945,
       1.01818377, 2.22827806, 0.25517406, 0.1953063 , 0.68733097,
       1.16584122, 0.09620062, 0.46659559, 1.0895638 , 0.37029682,
       0.37449738, 1.55775914, 0.8079596 , 1.39658727, 1.1803567 ,
       0.9634293 , 1.67568881, 1.53223192, 0.22063723, 0.46959879,
       1.60480931, 0.75189982, 0.53166497, 0.77773129, 0.24966819,
       0.52565857, 0.68563308, 0.38751126, 2.05309125, 0.61275144,
       2.04408164, 0.50844413, 0.45208011, 1.38237604, 0.06967233,
       0.45958812, 1.29397786, 0.27338956, 1.54855324, 0.01511416,
       1.15613479])

In [10]:
z_alcohol = scores.get_score(car_arr3[:, 2])
z_alcohol


array([0.43993758, 0.21131068, 0.18761539, 0.54740815, 0.8917629 ,
       0.63009543, 0.5833691 , 0.01564416, 1.92383077, 0.17768604,
       0.57636015, 1.33649909, 0.26270964, 0.31235637, 0.39821601,
       0.56175817, 0.3590827 , 0.02056875, 1.09702664, 0.20839028,
       0.51795224, 1.17796169, 0.54832435, 1.22819249, 0.33246702,
       0.34298044, 2.64542049, 0.19170394, 0.10676051, 0.8216734 ,
       1.02259663, 0.04743639, 0.77085851, 0.18761539, 3.00871772,
       0.05419338, 0.51645195, 0.91045343, 0.44110574, 0.39062298,
       2.8691228 , 0.8850059 , 0.44869877, 1.45156269, 1.79825375,
       0.4712259 , 0.85146144, 0.81115997, 1.03803464, 0.19437238,
       0.39788388])

In [11]:
# calculate average z-score for every car crash and create new array to save this data
vfunc = np.vectorize(get_average_score, otypes=[float])
out = vfunc(z_total, z_alcohol, z_speed)
out

array([0.78184364, 0.66331378, 0.5442557 , 0.88350666, 0.73998005,
       0.39454845, 0.6070513 , 0.23185734, 1.94825592, 0.43829271,
       0.54704824, 1.32790133, 0.21266296, 0.41343474, 0.46722126,
       0.58323291, 0.31590484, 0.6205493 , 1.1135203 , 0.24926506,
       0.56619851, 1.53180976, 0.59013552, 1.38048928, 0.652084  ,
       0.46077207, 1.89853095, 0.64734895, 0.19817055, 0.77264373,
       1.25069025, 0.47959204, 0.7192241 , 0.40425444, 1.74846861,
       0.33132486, 0.73634892, 0.67686874, 1.02821134, 0.71751356,
       2.30007479, 0.7593015 , 0.60324494, 1.2394644 , 0.98936315,
       0.48914797, 0.96752743, 0.78540769, 1.51636879, 0.23237118,
       0.64948135])

In [12]:
# choose top z-score
top = 7
# create new np array where crashes with top z-score are set to False and thr rest to True
k = np.where(out >= np.sort(out)[-top:][0], False, out)
k

array([0.78184364, 0.66331378, 0.5442557 , 0.88350666, 0.73998005,
       0.39454845, 0.6070513 , 0.23185734, 0.        , 0.43829271,
       0.54704824, 1.32790133, 0.21266296, 0.41343474, 0.46722126,
       0.58323291, 0.31590484, 0.6205493 , 1.1135203 , 0.24926506,
       0.56619851, 0.        , 0.59013552, 0.        , 0.652084  ,
       0.46077207, 0.        , 0.64734895, 0.19817055, 0.77264373,
       1.25069025, 0.47959204, 0.7192241 , 0.40425444, 0.        ,
       0.33132486, 0.73634892, 0.67686874, 1.02821134, 0.71751356,
       0.        , 0.7593015 , 0.60324494, 1.2394644 , 0.98936315,
       0.48914797, 0.96752743, 0.78540769, 0.        , 0.23237118,
       0.64948135])

In [13]:
c = np.where(k != False, True, k)
c

array([1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1.])

In [14]:
# create new array with our data and column that identify outliers
new_arr = np.column_stack((car_arr3, c))
new_arr

array([[18.8, 7.332000000000001, 5.64, 1.0],
       [18.1, 7.421, 4.525, 1.0],
       [18.6, 6.51, 5.208000000000001, 1.0],
       [22.4, 4.032, 5.824, 1.0],
       [12.0, 4.2, 3.36, 1.0],
       [13.6, 5.032, 3.808, 1.0],
       [10.8, 4.968, 3.888, 1.0],
       [16.2, 6.156000000000001, 4.86, 1.0],
       [5.9, 2.006, 1.5930000000000002, 0.0],
       [17.9, 3.759, 5.190999999999999, 1.0],
       [15.6, 2.964, 3.9, 1.0],
       [17.5, 9.45, 7.175, 1.0],
       [15.3, 5.508000000000001, 4.437, 1.0],
       [12.8, 4.6080000000000005, 4.352, 1.0],
       [14.5, 3.625, 4.205, 1.0],
       [15.7, 2.669, 3.925, 1.0],
       [17.8, 4.806, 4.272, 1.0],
       [21.4, 4.066, 4.922, 1.0],
       [20.5, 7.175, 6.765, 1.0],
       [15.1, 5.738, 4.53, 1.0],
       [12.5, 4.25, 4.0, 1.0],
       [8.2, 1.886, 2.87, 0.0],
       [14.1, 3.384, 3.948, 1.0],
       [9.6, 2.208, 2.784, 0.0],
       [17.6, 2.64, 5.456, 1.0],
       [16.1, 6.923000000000001, 5.474000000000001, 1.0],
       [21.4, 8.34599999

In [15]:
# visualize
while True:
    reason = ['total', 'speeding', 'alcohol']
    ch = int(input('If you want visualize data choose 1, to exit type smth else'))
    if ch == 1:
        y = int(input('Please input y axis \n'
              'If '+ reason[0] + ' input 0 \n'
              'If '+ reason[1] + ' input 1 \n'
              'If '+ reason[2] + ' input 2 \n'))
        x = int(input('Please input x axis \n'
              'If '+ reason[0] + ' input 0 \n'
              'If '+ reason[1] + ' input 1 \n'
              'If '+ reason[2] + ' input 2 \n'))

        plot = figure(title = "Statistic of car crashes", match_aspect = True)
        plot.title.align = "center"
        plot.title.text_font = "times"
        plot.title.text_font_style = "italic"
        plot.title.text_font_size = "25px"
        plot.xaxis.axis_label = reason[x]
        plot.yaxis.axis_label = reason[y]
        plot.axis.minor_tick_in = -3
        plot.axis.minor_tick_out = 6


        plot.scatter(new_arr[:, x][np.where(new_arr[:, -1] == False)], new_arr[:, y][np.where(new_arr[:, -1] == False)], size = 9, color = '#800000', alpha = 0.8)
        plot.scatter(new_arr[:, x][np.where(new_arr[:, -1] == True)], new_arr[:, y][np.where(new_arr[:, -1] == True)], size = 9, color = '#428af5', alpha = 0.8)

        output_file('numpy_scatter1.html')
        curdoc().theme = 'dark_minimal'
        show(plot)
    else:
        break
