In [89]:
import numpy as np
print(np.__version__)

1.20.1


In [90]:
# Enter your code here
a = np.arange(10)

# Visualization
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [91]:
arr = np.full((3, 3), True)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [92]:
# Extract all odd numbers from numpy.array.
# Input
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Enter your code here
result = arr[arr%2==1]

# Visualize
print('INPUT:')
print(arr)
print('OUTPUT:')
print(result)

INPUT:
[0 1 2 3 4 5 6 7 8 9]
OUTPUT:
[1 3 5 7 9]


In [93]:
# Replace all odd numbers in numpy.array with -1
import numpy as np

# Input
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# Visualize
print('INPUT:')
print(arr)

# Enter your code here
arr[arr%2==1] = -1
# Visualize
print('OUTPUT:')
print(arr)

INPUT:
[0 1 2 3 4 5 6 7 8 9]
OUTPUT:
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [94]:
#  Convert a 1D array to a 2D array with 2 rows.
import numpy as np

# Input
arr = np.arange(10)

# Enter your code here
result = arr.reshape(2,-1)

# Visualize
print('INPUT:')
print(arr)
print('OUTPUT:')
print(result)

INPUT:
[0 1 2 3 4 5 6 7 8 9]
OUTPUT:
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [95]:
# Find the mean, median, standard deviation of given 1D array.
import numpy as np

# Input
arr = np.array([1,2,3,4,5,6,7,8,9,10])

# Enter your code here
mu = np.mean(arr)
med = np.median(arr)
sd = np.std(arr)

# Output
print(arr)
print('RESULT:')
print("mean = ", mu, "; median = ", med, "; deviation = ", sd)

[ 1  2  3  4  5  6  7  8  9 10]
RESULT:
mean =  5.5 ; median =  5.5 ; deviation =  2.8722813232690143


In [96]:
# Find the 5th and 95th percentile of given array.
# Input
arr = np.array([1,2,3,4,5,6,7,8,9,10])
percentiles = [5, 95]

# Enter your code here
result = np.percentile(arr, q=percentiles)

# Output
print('INPUT:')
print(arr)
print('OUTPUT:')
print(result.round(2))

INPUT:
[ 1  2  3  4  5  6  7  8  9 10]
OUTPUT:
[1.45 9.55]


In [97]:
# Find the most frequent value in the given array.
arr = np.array([3, 4, 2, 1, 1, 1, 2, 3, 1, 3])

# Enter your code here
unique_values, indices_list = np.unique(arr, return_index=True)
result = unique_values[np.argmax(indices_list)]

# Output
print('INPUT:')
print(arr)
print('MOST FREQUENT VALUE:')
print(result)

INPUT:
[3 4 2 1 1 1 2 3 1 3]
MOST FREQUENT VALUE:
1


In [98]:
# Intermediate
# 1 Replace all odd numbers in arr with -1 without changing arr
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Enter your code here
out = np.where(arr % 2 == 1, -1, arr)

# Output
print('arr:')
print(arr)
print('out:')
print(out)

arr:
[0 1 2 3 4 5 6 7 8 9]
out:
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [99]:
# 2 Stack arrays a and b vertically
# Input
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Enter your code here
out = np.vstack((a,b))
# out = np.concatenate([a, b], axis=0)
# out = np.r_[a, b]
# Output
print('array a:')
print(a)
print('array b:')
print(b)
print('stacked:')
print(out)

array a:
[[0 1 2 3 4]
 [5 6 7 8 9]]
array b:
[[1 1 1 1 1]
 [1 1 1 1 1]]
stacked:
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [100]:
# 3 Stack the arrays a and b horizontally.

# Input
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Enter your code here
out = np.column_stack((a,b))

# Output
print('array a:')
print(a)
print('array b:')
print(b)
print('stacked:')
print(out)

array a:
[[0 1 2 3 4]
 [5 6 7 8 9]]
array b:
[[1 1 1 1 1]
 [1 1 1 1 1]]
stacked:
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [101]:
# 4 Create the following pattern without hardcoding. Use only numpy functions and the given array.
# Input
a = np.array([1,2,3])

# Enter your code here
out = np.r_['r', np.repeat(a, 3), np.tile(a, 3)]

# Output
print('a:')
print(a)
print('out:')
print(out)

a:
[1 2 3]
out:
[[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]]


In [102]:
# 5 Get the common items between a and b

# Input
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# Enter your code here
out = np.intersect1d(a,b)

# Output
print('a:')
print(a)
print('b:')
print(b)
print('out:')
print(out)

a:
[1 2 3 2 3 4 3 4 5 6]
b:
[ 7  2 10  2  7  4  9  4  9  8]
out:
[2 4]


In [103]:
# 6 From array a remove all items present in array b.

# Input
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

# Enter your code here
out = np.setdiff1d(a,b)

# Output
print('a:')
print(a)
print('b:')
print(b)
print('out:')
print(out)

a:
[1 2 3 4 5]
b:
[5 6 7 8 9]
out:
[1 2 3 4]


In [104]:
# 7 Get the positions where elements of a and b match.

# Input
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

# Enter your code here
out = np.where(a==b)[0]

# Output
print('a:')
print(a)
print('b:')
print(b)
print('out:')
print(out)

a:
[1 2 3 2 3 4 3 4 5 6]
b:
[ 7  2 10  2  7  4  9  4  9  8]
out:
[1 3 5 7]


In [105]:
# 8 Get all items between 5 and 10 from a.

# Input
a = np.array([2, 6, 1, 9, 10, 3, 27])

# Enter your code here
out = a[np.where((a>=5) & (a <= 10))]

# Output
print('a:')
print(a)
print('out:')
print(out)

a:
[ 2  6  1  9 10  3 27]
out:
[ 6  9 10]


In [106]:
# 9 Convert the function maxx that works on two scalars to work on two arrays.

# Input
def maxx(x, y):
    """Get the maximum of two items"""
    return x if x >= y else y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

# Enter your code here
vfunc = np.vectorize(maxx, otypes=[int])
out = vfunc(a,b)

# Output
print('a:')
print(a)
print('b:')
print(b)
print('out:')
print(out)

a:
[5 7 9 8 6 4 5]
b:
[6 3 4 8 9 7 1]
out:
[6 7 9 8 9 7 5]


In [107]:
# 10 Swap columns 1 and 2 in the numpy.array.

# Input
arr = np.array([[0, 1, 2],
                [3, 4, 5],
                [6, 7, 8]])

# Enter your code here
out = arr[:, [1,0,2]]

# Output
print('arr:')
print(arr)
print('out:')
print(out)

arr:
[[0 1 2]
 [3 4 5]
 [6 7 8]]
out:
[[1 0 2]
 [4 3 5]
 [7 6 8]]


In [108]:
# 11 Swap rows 1 and 2 in the numpy array.

# Input
arr = np.array([[3, 4, 5],
                [0, 1, 2],
                [6, 7, 8]])

# Enter your code here
out = arr[[1,0,2], : ]

# Output
print('arr:')
print(arr)
print('out:')
print(out)

arr:
[[3 4 5]
 [0 1 2]
 [6 7 8]]
out:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [109]:
# 12 Reverse the rows of a 2D array.

# Input
arr = np.array([[3, 4, 5],
                [0, 1, 2],
                [6, 7, 8]])

# Enter your code here
out = arr[::-1]

# Output
print('arr:')
print(arr)
print('out:')
print(out)

arr:
[[3 4 5]
 [0 1 2]
 [6 7 8]]
out:
[[6 7 8]
 [0 1 2]
 [3 4 5]]


In [110]:
# 13 Reverse the columns of a 2D array arr.

# Input
arr = np.array([[3, 4, 5],
                [0, 1, 2],
                [6, 7, 8]])

# Enter your code here
out = arr[:,::-1]

# Output
print('arr:')
print(arr)
print('out:')
print(out)

arr:
[[3 4 5]
 [0 1 2]
 [6 7 8]]
out:
[[5 4 3]
 [2 1 0]
 [8 7 6]]


In [111]:
# 14 Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

# Enter your code here
rand_arr = np.random.uniform(5,10, size=(5,3))

# Output
print(rand_arr.round(2))

[[5.35 8.18 8.12]
 [6.3  9.55 7.44]
 [8.07 7.71 5.36]
 [6.9  9.64 8.8 ]
 [9.76 8.72 5.17]]


In [112]:
# 15 Given 2D array extract one column with specified index.

# Input:
arr = np.array([[1,2,3,4,5],
                [1,2,3,4,5],
                [1,2,3,4,5],
                [1,2,3,4,5]])
extract_column_idx = 4

# Enter your code here
extracted = arr[:,4]

# Output:
print('array:')
print(arr)
print('extracted:')
print(extracted)

array:
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
extracted:
[5 5 5 5]


In [113]:
# 16 Given array of tuples extract column specified by given index.

# Input:
arr = np.array([(1,2,3,4,5),
                (1,2,3,4,5),
                (1,2,3,4,5),
                (1,2,3,4,5)])

# Enter your code here
extracted = np.array([i[4] for i in arr])

# Output:
print('array:')
print(arr)
print('extracted:')
print(extracted)

array:
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
extracted:
[5 5 5 5]


In [114]:
# 17 normalize an array so the values range exactly between 0 and 1

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Enter your code here
arr_norm = (arr - arr.min())/(arr.max() - arr.min())

# Output:
print('array:')
print(arr)
print('normalized:')
print(arr_norm.round(2))

array:
[ 1  2  3  4  5  6  7  8  9 10]
normalized:
[0.   0.11 0.22 0.33 0.44 0.56 0.67 0.78 0.89 1.  ]


In [115]:
# 18 Insert np.nan values at 2 random positions in given array.

matr = np.array([[1.,2.,3.],
                 [1.,2.,3.],
                 [1.,2.,3.]])
print('BEFORE INSERT:')
print(matr)

# Enter your code here
matr[np.random.randint(3, size= 2), np.random.randint(3,size=2)] = np.nan

# Output
print('AFTER INSERT:')
print(matr)

BEFORE INSERT:
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
AFTER INSERT:
[[ 1. nan  3.]
 [nan  2.  3.]
 [ 1.  2.  3.]]


In [116]:
# 19 Find the number and position of missing values in given 2D array.

matr = np.array([[np.nan,     2.,    3. ],
                 [    1., np.nan,    3. ],
                 [     1.,    2., np.nan]])
print('input:')
print(matr)

# Enter your code here
n_mis = np.isnan(matr[:,:]).sum()
idx_mis = np.where(np.isnan(matr[:,:]))

# Output
print("Array is missing ", n_mis, " values with indices:")
print(np.array(idx_mis))

input:
[[nan  2.  3.]
 [ 1. nan  3.]
 [ 1.  2. nan]]
Array is missing  3  values with indices:
[[0 1 2]
 [0 1 2]]


In [117]:
# 20 Find the correlation between column x and column y of the given 2D array.

matr = np.array([[0, 0, 0, 2, 2],
                 [0, 2, 1, 2, 2],
                 [2, 2, 1, 0, 0],
                 [0, 0, 2, 0, 1],
                 [1, 2, 2, 0, 0]])
x = 0
y = 3
print('input:')
print(matr)

# Enter your code here
corr = np.corrcoef(matr[:,x],matr[:,y])[1,0]

# Output
print('Correlation between column ', x, ' and column ', y, ' is ', corr)

input:
[[0 0 0 2 2]
 [0 2 1 2 2]
 [2 2 1 0 0]
 [0 0 2 0 1]
 [1 2 2 0 0]]
Correlation between column  0  and column  3  is  -0.6123724356957946


In [118]:
# 21 Find out if given array has any missing values (i.e. np.nan are present).

matr = np.array([[1.0,    2.0],
                 [np.nan, 4.0]])
print(matr)

# Enter your code here
flag = np.where( np.isnan)
# flag = np.isnan(matr).any()

# Output
if flag:
  print('found nans')
else:
  print('no nans were found')


[[ 1.  2.]
 [nan  4.]]
found nans


In [119]:
# 22 Replace all occurrences of np.nan with 0 in 2D array

matr = np.array([[1.0,    2.0],
                 [np.nan, 4.0]])
print('INITIAL ARRAY:')
print(matr)

# Enter your code here
matr[np.isnan(matr)] = 0

# Output
print('PROCESSED ARRAY:')
print(matr)

INITIAL ARRAY:
[[ 1.  2.]
 [nan  4.]]
PROCESSED ARRAY:
[[1. 2.]
 [0. 4.]]


In [120]:
# 23 Find the unique values and the count of unique values in given array.

arr = np.array([1,2,3,1,2,4])
print('INITIAL ARRAY:')
print(arr)

# Enter your code here
uniques, counts = np.unique(arr, return_counts=True)

# Output
print('UNIQUE ELEMENTS:')
print(uniques)
print('THEIR COUNTS:')
print(counts)

INITIAL ARRAY:
[1 2 3 1 2 4]
UNIQUE ELEMENTS:
[1 2 3 4]
THEIR COUNTS:
[2 2 1 1]


In [121]:
# 24 convert a numeric to a categorical (text) array
height_arr = np.array([1.80, 2.10, 1.90, 1.60, 1.70, 1.65, 1.75])
bins = [0.0, 1.7, 1.85, 2.0]
label_map = ['short', 'medium', 'tall', 'alien']

# Enter your code here
height_labels = [label_map[x-1] for x in np.digitize(height_arr, bins)]

# Output
# from google.colab import data_table
import pandas as pd
pd.DataFrame([height_arr, height_labels], index=['Heights:', 'Labels:'])

0      1     2      3       4      5       6
Heights:     1.8    2.1   1.9    1.6     1.7   1.65    1.75
Labels:   medium  alien  tall  short  medium  short  medium

In [122]:
# 25 An array that contains width, length, and height of parallelepipedal bars is given. Add one more column to the array that should contain volume of the appropriate bar.

arr = np.array([[5.7, 4.3, 9.8],
                [1.0, 2.0, 1.6],
                [6.5, 2.5, 4.6]])
print('INITIAL ARRAY:')
print(arr)

# Enter your code here
volume = arr[:, 0] * arr[:, 1] * arr[:, 2]
arr = np.column_stack([arr, volume[:, np.newaxis]])

# Output
print('VOLUME ADDED:')
print(arr.round(2))

INITIAL ARRAY:
[[5.7 4.3 9.8]
 [1.  2.  1.6]
 [6.5 2.5 4.6]]
VOLUME ADDED:
[[  5.7    4.3    9.8  240.2 ]
 [  1.     2.     1.6    3.2 ]
 [  6.5    2.5    4.6   74.75]]


In [123]:
# 26  An array that contains student's name and number of solved problems is given. Find the second largest number of problems that Alice has solved.

arr = np.array([['Alice', 7],
                ['Bob',   1],
                ['Alice', 3],
                ['Alice', 2],
                ['Alice', 5],
                ['Bob',   9],
                ['Bob',   1],
                ['Alice', 6],
                ['Bob',   6],
                ['Alice', 3],
                ['Alice', 1]])
student = 'Alice'

# from google.colab import data_table
import pandas as pd
# dt = data_table.DataTable(pd.DataFrame(arr.T, index=['Name', 'Problems solved']))
# import IPython
# display(IPython.display.HTML(dt._repr_html_()))

# Enter your code here
filtered = arr[arr[:, 0] == student, [1]].astype('float')
result = np.unique(np.sort(filtered))[-2]
# pd.DataFrame([arr[0][i] , arr[1][i]] for i in range(arr))
# Output
print('The second largest number of problems ', student, ' has solved is ', result)

The second largest number of problems  Alice  has solved is  6.0


In [124]:
# 27  Find the position of the first occurrence of a value strictly greater than given threshold.

arr = np.array([8, 5, 2, 7, 5, 9, 0, 9, 8, 6, 2, 0, 5, 3, 10, 2, 3, 6, 4, 1])
threshold = 8
print('input:')
print(arr)

# Enter your code here
idx = np.argwhere(arr>threshold)[0][0]

# Output
print('The first value higher than ', threshold, ' occurs at ', idx, '-th position')

input:
[ 8  5  2  7  5  9  0  9  8  6  2  0  5  3 10  2  3  6  4  1]
The first value higher than  8  occurs at  5 -th position


In [125]:
# 28 replace all values greater than a given value to a given cutoff?

a = np.array([27.6, 14.6, 21.8, 42.3,  1.2,
               6.9, 33.8, 41.4,  7.7,  29.1,
              44.6, 11.2, 10.0,  6.3,  11.7,
              48.9, 40.7,  9.4, 41.0 , 14.4])
min_cut = 10
max_cut = 30

# Enter your code here
new_a = np.clip(a, a_min=min_cut, a_max=max_cut)

# Output
print('initial array')
print(a)
print('cutoff array')
print(new_a)

initial array
[27.6 14.6 21.8 42.3  1.2  6.9 33.8 41.4  7.7 29.1 44.6 11.2 10.   6.3
 11.7 48.9 40.7  9.4 41.  14.4]
cutoff array
[27.6 14.6 21.8 30.  10.  10.  30.  30.  10.  29.1 30.  11.2 10.  10.
 11.7 30.  30.  10.  30.  14.4]


In [126]:
# 29 Get the positions of top 5 maximal values in a given array.

a = np.array([4, 13, 5, 8, 17, 12, 11, 14, 19, 1, 2, 0, 9, 6, 16, 18, 7, 3, 10, 15])

# Enter your code here
idx = a.argsort()[-5:]
# idx = np.argpartition(-a, 5)[:5]
# Output
print('initial array')
print(a)
print('5 maximal value indices')
print(idx)

initial array
[ 4 13  5  8 17 12 11 14 19  1  2  0  9  6 16 18  7  3 10 15]
5 maximal value indices
[19 14  4 15  8]


In [127]:
# 30 Create ranks for the given numeric array.

a = np.array([9, 4, 15, 0, 17, 16, 17, 8, 9, 0])

# Enter your code here
rank = a.argsort().argsort()

# Output
print('initial array')
print(a)
print('ranks')
print(rank)

initial array
[ 9  4 15  0 17 16 17  8  9  0]
ranks
[4 2 6 0 8 7 9 3 5 1]


In [128]:
# 31 Compute the maximum for each row of the given array.

# Input
a = np.array([[9, 9, 4],
              [8, 8, 1],
              [5, 3, 6]])

# Enter your code here
maximas = np.amax(a,axis=1)

# Output
print('initial array')
print(a)
print('maximas')
print(maximas)

initial array
[[9 9 4]
 [8 8 1]
 [5 3 6]]
maximas
[9 8 6]


In [129]:
# 32 Drop all nan values from a 1D numpy array.

# Input
a = np.array([1,2,3,np.nan,5,6,7,np.nan])

# Enter your code here
after_drop = a[~np.isnan(a)]

# Output
print('initial array')
print(a)
print('nans dropped')
print(after_drop)

initial array
[ 1.  2.  3. nan  5.  6.  7. nan]
nans dropped
[1. 2. 3. 5. 6. 7.]


In [130]:
# 33 Subtract the 1d array from the 2d array. Each item of b_1d should be subtracted from respective row of a_2d.

# Input
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])

# Enter your code here
result = a_2d - b_1d[:,None]

# Output
print('from')
print(a_2d)
print('subtract')
print(b_1d)
print('result')
print(result)

from
[[3 3 3]
 [4 4 4]
 [5 5 5]]
subtract
[1 2 3]
result
[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [131]:
# 34 Find the index of 5th repetition of number 1 in x.

# Input:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
n = 5

# Enter your code here
# idx = [i for i, v in enumerate(x) if v == 1][n-1]

idx = np.where(x==1)[0][n-1]

print('initial array')
print(x)
print('index of the ', n, '-th repetition of 1 is ', idx)

initial array
[1 2 1 1 3 4 3 1 1 2 1 1 2]
index of the  5 -th repetition of 1 is  8


In [132]:
# 35 Create a numpy array of given length that starts with given number and has a given step between consecutive numbers.
# Input
length = 10
start  = 5
step   = 3

# Enter your code here
arr = np.arange(start,start + step* length, step)

# Output
print(arr)


[ 5  8 11 14 17 20 23 26 29 32]
